#!/usr/bin/perl -w -T

#-----------------------------------------------------------------------------
#
#  Copyright (c) 2017 Ryan C. Gordon.
#
#  This software is provided 'as-is', without any express or implied warranty.
#  In no event will the authors be held liable for any damages arising from
#  the use of this software.
#
#  Permission is granted to anyone to use this software for any purpose,
#  including commercial applications, and to alter it and redistribute it
#  freely, subject to the following restrictions:
#
#  1. The origin of this software must not be misrepresented; you must not
#  claim that you wrote the original software. If you use this software in a
#  product, an acknowledgment in the product documentation would be
#  appreciated but is not required.
#
#  2. Altered source versions must be plainly marked as such, and must not be
#  misrepresented as being the original software.
#
#  3. This notice may not be removed or altered from any source distribution.
#
#      Ryan C. Gordon <icculus@icculus.org>
#
#-----------------------------------------------------------------------------

use warnings;
use strict;

sub send_gopher_menu {
    my ($itemtype, $str, $selector, $host, $port) = @_;
    $itemtype = 'i' if not defined $itemtype;
    $str = '' if not defined $str;
    $selector = '' if not defined $selector;
    $host = 'error.host' if not defined $host;
    $port = 1 if not defined $port;
    print("$itemtype$str\t$selector\t$host\t$port\r\n");
}

sub send_gopher_info {
    my $str = shift;
    send_gopher_menu('i', $str);
}

send_gopher_info('Here are some things you can try here:');
send_gopher_info('');

my $seen = 0;
my $gopherspace = $ENV{'GOPHERSPACE'};
if (opendir(my $dh, $gopherspace)) {
    while (readdir($dh)) {
        my $f = "$gopherspace/$_";
        next if not -f $f;
        next if not -x $f;
        next if $_ eq 'default';
        send_gopher_menu('1', $_, $_, $ENV{'GOPHERHOST'}, $ENV{'GOPHERPORT'});
        $seen = 1;
    }
    closedir($dh);
}

send_gopher_menu(3, '   ...nothing, apparently!') if !$seen;

