#!/usr/bin/perl -w

use strict;
use warnings;

sub send_gopher_menu {
    my ($itemtype, $str, $selector, $host, $port) = @_;
    $itemtype = 'i' if not defined $itemtype;
    $str = '' if not defined $str;
    $selector = '' if not defined $selector;
    $host = 'error.host' if not defined $host;
    $port = 1 if not defined $port;
    print("$itemtype$str\t$selector\t$host\t$port\r\n");
}

sub send_gopher_info {
    my $str = shift;
    send_gopher_menu('i', $str);
}

my @lines = split /^/m, `/usr/games/fortune`;
if (scalar(@lines) == 0) {
     send_gopher_menu('3', "Uhoh, fortune process didn't work out. Sorry!");
     exit(1);
}

send_gopher_info('');
send_gopher_info('');
foreach (@lines) {
    chomp;
    s/\t/    /g;
    send_gopher_info($_);
}
send_gopher_info('');
send_gopher_info('');

