#!/usr/bin/perl -w

#-----------------------------------------------------------------------------
#
#  Copyright (c) 2017 Ryan C. Gordon.
#
#  This software is provided 'as-is', without any express or implied warranty.
#  In no event will the authors be held liable for any damages arising from
#  the use of this software.
#
#  Permission is granted to anyone to use this software for any purpose,
#  including commercial applications, and to alter it and redistribute it
#  freely, subject to the following restrictions:
#
#  1. The origin of this software must not be misrepresented; you must not
#  claim that you wrote the original software. If you use this software in a
#  product, an acknowledgment in the product documentation would be
#  appreciated but is not required.
#
#  2. Altered source versions must be plainly marked as such, and must not be
#  misrepresented as being the original software.
#
#  3. This notice may not be removed or altered from any source distribution.
#
#      Ryan C. Gordon <icculus@icculus.org>
#
#-----------------------------------------------------------------------------

use strict;
use warnings;

sub send_gopher_menu {
    my ($itemtype, $str, $selector, $host, $port) = @_;
    $itemtype = 'i' if not defined $itemtype;
    $str = '' if not defined $str;
    $selector = '' if not defined $selector;
    $host = 'error.host' if not defined $host;
    $port = 1 if not defined $port;
    print("$itemtype$str\t$selector\t$host\t$port\r\n");
}

sub send_gopher_info {
    my $str = shift;
    send_gopher_menu('i', $str);
}

my @lines = split /^/m, `/usr/games/fortune`;
if (scalar(@lines) == 0) {
     send_gopher_menu('3', "Uhoh, fortune process didn't work out. Sorry!");
     exit(1);
}

send_gopher_info('');
send_gopher_info('');
foreach (@lines) {
    chomp;
    s/\t/    /g;
    send_gopher_info($_);
}
send_gopher_info('');
send_gopher_info('');

print(".\r\n");

